---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        types: [json,yaml]
  - repo: local
    hooks:
      - id: rnc-format-validate
        name: Check rnc schema files
        entry: hooks/rnc-format-validate.py
        language: python
        files: schemas/styles/csl*.rnc
